### ISSUE TITLE
Please migrate to github

### ISSUE THREAD

**Issue by GoogleCodeExporter** [npcole/npyscreen#26]
```
As now widely known, google code is dying, please migarte to github. There's an 
"Export to Github" button on the main project page.

```

Original issue reported on code.google.com by `qop...@gmail.com` on 19 Apr 2015 at 10:37

**Comment by npcole** [comment]
There is now an official respoitory at Bitbucket and this one at GitHub. I'll be keeping both in sync with each other. If one ends up being much more useful than the other, I'll keep the most used one.
