### ISSUE TITLE
Long Word Line Breaking Error

### ISSUE THREAD

**Issue by will-mei** [npcole/npyscreen#78]
if the word is longer than the width of widget width the line breaking error apears.

![line_breaking_error](https://user-images.githubusercontent.com/24793917/56281126-644ac880-613e-11e9-88b2-b882acf7c768.png)

at first I thought it was caused by the chinese character I used, even after I fix the width calculation error of Chinese char in wgtextbox.py, the problem is still, so I found out there is not \n inserted if the word is too long, and that cause the line breaking problem.

I suggest to define a new TextfieldBase widget, I am working on that but I need help.

**Comment by will-mei** [comment]
Fixed, I'll try to commit the code as soon as my project is finished.

**Comment by npcole** [comment]
That's very odd.
