### ISSUE TITLE
[BUG]: GridColTitles inside BoxTitle: Titles not showing up.

### ISSUE THREAD

**Issue by Fran6nd** [npcole/npyscreen#87]
The issue is simple:
Using a `GridColTitles` inside `BoxTitle` via `_contained_widget` won't show up titles.
It works as expected with any others wigget I tryed... It seems borders of `BoxTitles`are overwriting titles.

**Comment by jerome-diver** [comment]
Did you also try to, first, define a width and height of GridColTitles ?

**Comment by Fran6nd** [comment]
I'll do so right now!
